
import { createClient } from '@supabase/supabase-js';

export class DBService {
  private client: any = null;

  init(url: string, key: string) {
    try {
      if (!url || !key) return false;
      this.client = createClient(url, key);
      return true;
    } catch (e) {
      console.error("初始化 Supabase 客户端失败", e);
      return false;
    }
  }

  async testConnection() {
    if (!this.client) return false;
    try {
      const { error } = await this.client.from('prompts').select('id', { count: 'exact', head: true }).limit(1);
      if (error) {
        console.warn("数据库请求返回错误:", error);
        return false;
      }
      return true;
    } catch (e) {
      console.error("数据库连接测试失败", e);
      return false;
    }
  }

  async listPrompts() {
    if (!this.client) throw new Error("数据库未连接");
    const { data, error } = await this.client
      .from('prompts')
      .select('id, name, created_at')
      .order('created_at', { ascending: false });
    
    if (error) throw error;
    return data;
  }

  async getPromptById(id: number) {
    if (!this.client) throw new Error("数据库未连接");
    const { data, error } = await this.client
      .from('prompts')
      .select('*')
      .eq('id', id)
      .single();
    
    if (error) throw error;
    return data;
  }

  async savePrompt(name: string, content: string) {
    if (!this.client) throw new Error("数据库未连接，请先在配置页测试连接。");
    const { data, error } = await this.client
      .from('prompts')
      .insert([{ name, content, updated_at: new Date().toISOString() }]);
    
    if (error) {
      console.error("保存失败:", error);
      throw new Error(error.message);
    }
    return data;
  }

  getSQLSchema() {
    return `
-- 在 Supabase SQL Editor 中运行以下脚本
CREATE TABLE IF NOT EXISTS prompts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 启用行级安全 (RLS)
ALTER TABLE prompts ENABLE ROW LEVEL SECURITY;

-- 允许匿名公开读写
CREATE POLICY "Public Access" ON prompts FOR ALL USING (true) WITH CHECK (true);
    `.trim();
  }
}

export const dbService = new DBService();
